# Tensor

2D Tensor = (batchsize, dimension)  
3D Tensor = (batchsize, length, dimension)

In [2]:
import torch
import numpy as np

In [24]:
# numpy 2D
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.], 
              [10., 11., 12.]])

print("Rank of t:", t.ndim)
print("shape of t:", t.shape)

Rank of t: 2
shape of t: (4, 3)


In [25]:
t[:, 2:]

array([[ 3.],
       [ 6.],
       [ 9.],
       [12.]])

In [26]:
# torch 2D
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.], 
                       [10., 11., 12.]])

print("Rank of t:", t.ndim)
print("shape of t:", t.shape)

Rank of t: 2
shape of t: torch.Size([4, 3])


In [27]:
t[:, 2:]

tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])

In [30]:
# BroadCasting
a = t[:, 2:]
print(a+t)

tensor([[ 4.,  5.,  6.],
        [10., 11., 12.],
        [16., 17., 18.],
        [22., 23., 24.]])


In [38]:
# Matrix Multiplication VS element-wise mul
m1 = torch.FloatTensor([[1, 2], 
                        [3, 4]])
                        
m2 = torch.FloatTensor([[3, 1], 
                        [0, 2]])
print("Matrix Multiplication:\n", m1.matmul(m2), "\n")
print("element-wise Multiplication by *:\n", m1 * m2, "\n")
print("element-wise Multiplication by mul:\n", m1.mul(m2))

Matrix Multiplication:
 tensor([[ 3.,  5.],
        [ 9., 11.]]) 

element-wise Multiplication by *:
 tensor([[3., 2.],
        [0., 8.]]) 

element-wise Multiplication by mul:
 tensor([[3., 2.],
        [0., 8.]])


In [39]:
t_mean = m1.mean()
print(t_mean)

tensor(2.5000)


In [40]:
t_mean = m1.mean(dim=0)
print(t_mean)

tensor([2., 3.])


In [41]:
t_mean = m1.mean(dim=1)
print(t_mean)

tensor([1.5000, 3.5000])


In [43]:
t_sum = m1.sum()
print(t_sum)

tensor(10.)


In [44]:
t_sum = m1.sum(dim=0)
print(t_sum)

tensor([4., 6.])


In [49]:
t_max = m1.max(dim=0)
print(t_max)
print(t_max[0])
print(t_max[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
