# Linear Regression

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(w)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [6]:
hypothesis = X_train*w + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
# cost = MSE
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
optimizer = optim.SGD([w, b], lr=0.01)
optimizer.zero_grad() # 기울기 누적 방지를 위해 초기화함
cost.backward()
optimizer.step()

In [15]:
nb_epochs = 200
for epoch in range(nb_epochs + 1):

    hypothesis = X_train * w
    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w.item(), b.item(), cost.item()
        ))


Epoch    0/200 W: 2.000, b: 0.080 Cost: 0.000000
Epoch  100/200 W: 2.000, b: 0.080 Cost: 0.000000
Epoch  200/200 W: 2.000, b: 0.080 Cost: 0.000000


In [19]:
print(w)
print(b)

tensor([2.0000], requires_grad=True)
tensor([0.0800], requires_grad=True)


In [22]:
w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

z.backward()

print(w.grad)

tensor(8.)
