# Padding
#### for parallel computing

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [8]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [9]:
max_len = max(len(item) for item in encoded)
print(max_len)

7


In [10]:
for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)

padded_up = np.array(encoded)
print(padded_up)

[[ 1  5  0  0  0  0  0]
 [ 1  8  5  0  0  0  0]
 [ 1  3  5  0  0  0  0]
 [ 9  2  0  0  0  0  0]
 [ 2  4  3  2  0  0  0]
 [ 3  2  0  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  2  0  0  0  0]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13  0  0  0]]


In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [28]:
print(pad_sequences(encoded, padding='post',truncating='post', maxlen=5, value=4))

[[ 1  5  4  4  4]
 [ 1  8  5  4  4]
 [ 1  3  5  4  4]
 [ 9  2  4  4  4]
 [ 2  4  3  2  4]
 [ 3  2  4  4  4]
 [ 1  4  6  4  4]
 [ 1  4  6  4  4]
 [ 1  4  2  4  4]
 [ 7  7  3  2 10]
 [ 1 12  3 13  4]]
