# Splitting Data

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [3]:
X = df['메일 본문']
y = df['스팸 메일 유무']

In [4]:
print(X)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object


In [5]:
print(y)

0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


In [12]:
np_array = np.arange(0,16).reshape((4,4))
X = np_array[:, :3]
y = np_array[:, 3]
print(np_array)
print()
print(X)
print()
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[ 3  7 11 15]


### Split by using sklearn

In [16]:
# X=feature, y=label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [20]:
X, y = np.arange(10).reshape((5, 2)), range(5)
print("X\n", X)
print()
print("y\n", list(y))

X
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

y
 [0, 1, 2, 3, 4]


In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
print("X_train\n", X_train)
print()
print("X_test\n", y_train)

X_train
 [[6 7]
 [8 9]
 [0 1]
 [4 5]]

X_test
 [3, 4, 0, 2]
